apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkflow
resources:
  - namespace.yaml
  - configmap.yaml
  - services.yaml
  - hpa.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/part-of: linkflow
